

  CREATE TABLE "PERSISTENT_LOGINS" 
   (	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"SERIES" VARCHAR2(50) NOT NULL ENABLE, 
	"TOKEN" VARCHAR2(100) NOT NULL ENABLE, 
	"LAST_USED" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PR_MEMBER" 
   (	"USERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"USERPW" NVARCHAR2(200) NOT NULL ENABLE, 
	"PHONE" NVARCHAR2(100) NOT NULL ENABLE, 
	"ADDRESS" NVARCHAR2(200) NOT NULL ENABLE, 
	"JOB" NVARCHAR2(200), 
	"ACCOUNT" NVARCHAR2(100), 
	"PROFILE_IMAGE" NVARCHAR2(400), 
	"INTERESTING_CATEGORY" NVARCHAR2(200), 
	"SELF_INTRODUCE" NVARCHAR2(2000), 
	"NAME" NVARCHAR2(200) NOT NULL ENABLE, 
	"BANK" NVARCHAR2(200), 
	"NICKNAME" NVARCHAR2(200) NOT NULL ENABLE, 
	"AUTH" VARCHAR2(100), 
	 CONSTRAINT "XPKPR_MEMBER" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PR_INQURY" 
   (	"INQURY_NUM" NUMBER NOT NULL ENABLE, 
	"TITLE" NVARCHAR2(200) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ATTACH" NVARCHAR2(400), 
	"USERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"RIPPLE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CONTENT" NVARCHAR2(2000), 
	"RIPPLE_CONTENT" NVARCHAR2(2000), 
	"RIPPLE_CHECK" CHAR(1) DEFAULT 'N', 
	 CONSTRAINT "XPKPR_INQURY" PRIMARY KEY ("INQURY_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PR_R_10" FOREIGN KEY ("USERID")
	  REFERENCES "PR_MEMBER" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PR_NOTICE" 
   (	"NOTICE_NUM" NUMBER NOT NULL ENABLE, 
	"TITLE" NVARCHAR2(200) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ATTACH" NVARCHAR2(400), 
	"USERID" NVARCHAR2(100), 
	"CONTENT" NVARCHAR2(2000), 
	 CONSTRAINT "XPKPR_NOTICE" PRIMARY KEY ("NOTICE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PR_R_33" FOREIGN KEY ("USERID")
	  REFERENCES "PR_MEMBER" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PR_PROJECT" 
   (	"PROJECT_NUM" NUMBER NOT NULL ENABLE, 
	"CATEGORY" NVARCHAR2(200), 
	"TITLE_IMAGE" NVARCHAR2(400), 
	"SIMPLE_CONTENT" NVARCHAR2(2000), 
	"PHONE" NVARCHAR2(100) NOT NULL ENABLE, 
	"USERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"PROJECT_START" DATE DEFAULT SYSDATE, 
	"PROJECT_END" DATE DEFAULT SYSDATE, 
	"PROJECT_MODIFIED" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ATTACH_1" NVARCHAR2(400), 
	"ATTACH_2" NVARCHAR2(400), 
	"ATTACH_3" NVARCHAR2(400), 
	"DETAIL_CONTENT" NVARCHAR2(2000), 
	"PROJECT_RECORD" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"COMPANY" NVARCHAR2(200) NOT NULL ENABLE, 
	"CONTENTS_IMAGE1" NVARCHAR2(400), 
	"CONTENTS_IMAGE2" NVARCHAR2(400), 
	"CURRENT_INVEST" NUMBER DEFAULT 0, 
	"ACHIVE_INVEST" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"PROJECT_DISTINCT" NVARCHAR2(100), 
	 CONSTRAINT "XPKPR_PROJECT" PRIMARY KEY ("PROJECT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PR_R_19" FOREIGN KEY ("USERID")
	  REFERENCES "PR_MEMBER" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PR_RIPPLE" 
   (	"REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USERID" NVARCHAR2(100) NOT NULL ENABLE, 
	"CONTENT" NVARCHAR2(2000), 
	"RIPPLE_NUM" NUMBER NOT NULL ENABLE, 
	"PROJECT_NUM" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "XPKPR_RIPPLE" PRIMARY KEY ("RIPPLE_NUM", "PROJECT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PR_R_14" FOREIGN KEY ("PROJECT_NUM")
	  REFERENCES "PR_PROJECT" ("PROJECT_NUM") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "PR_R_20" FOREIGN KEY ("USERID")
	  REFERENCES "PR_MEMBER" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PR_RIPPLE_RIPPLE" 
   (	"REG_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"USERID" NVARCHAR2(100), 
	"CONTENT" NVARCHAR2(2000), 
	"RIPPLE_NUM" NUMBER NOT NULL ENABLE, 
	"PROJECT_NUM" NUMBER NOT NULL ENABLE, 
	"RIPPLE_RIPPLE_NUM" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "XPKPR_RIPPLE_RIPPLE" PRIMARY KEY ("RIPPLE_NUM", "PROJECT_NUM", "RIPPLE_RIPPLE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PR_R_15" FOREIGN KEY ("RIPPLE_NUM", "PROJECT_NUM")
	  REFERENCES "PR_RIPPLE" ("RIPPLE_NUM", "PROJECT_NUM") ENABLE, 
	 CONSTRAINT "PR_R_25" FOREIGN KEY ("USERID")
	  REFERENCES "PR_MEMBER" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "PR_INVESTOR" 
   (	"SCORE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"JOB" NVARCHAR2(200), 
	"USERID" NVARCHAR2(100), 
	"INVEST_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"PROJECT_NUM" NUMBER NOT NULL ENABLE, 
	"INVESTOR_NUM" NUMBER NOT NULL ENABLE, 
	"AMOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "XPKPR_INVESTOR" PRIMARY KEY ("INVESTOR_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "PR_R_23" FOREIGN KEY ("PROJECT_NUM")
	  REFERENCES "PR_PROJECT" ("PROJECT_NUM") ENABLE, 
	 CONSTRAINT "PR_R_28" FOREIGN KEY ("USERID")
	  REFERENCES "PR_MEMBER" ("USERID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE SEQUENCE  "SEQ_INQURY"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SEQ_INVESTOR"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SEQ_MEMBER"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SEQ_NOTICE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SEQ_PROJECT"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SEQ_RIPPLE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "SEQ_RIPPLE_RIPPLE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;